[package]
name = "ytk"
version = "0.1.0"
std = 20

[dependencies]
boost = { version = "1.81.0", components = ["headers", "log", "system", "filesystem", "thread"] }
qt = { version = "5.15.9", components = ["Core", "Gui", "Widgets"] }

[profile]
definitions = ["BOOST_PROCESS_USE_STD_FS", "FUSION_MAX_VECTOR_SIZE=30", "BOOST_SPIRIT_USE_PHOENIX_V3", "BOOST_SPIRIT_UNICODE", "BOOST_SPIRIT_NO_PREDEFINED_TERMINALS", "BOOST_LOG_WITHOUT_WCHAR_T", "BOOST_SPIRIT_UNICODE"]

[target.'cfg(not(compiler = "msvc"))'.profile]
cxxflags = ["-Wall", "-Wextra", "-Werror", "-Wfatal-errors", "-Wno-unused-parameter", "-Wno-missing-field-initializers"]

debug = { ubsan = true }

[target.'cfg(os = "macos")'.profile]
definitions = ["BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED"]

# macos with gcc11 has bugs in asan:
# `member call on address 0x60b0000001a0 which does not point to an object of type '_Sp_counted_base'`
[target.'cfg(any(os = "linux", compiler = "clang", compiler = "apple_clang"))'.profile.debug]
asan = true

[target.'cfg(compiler = "msvc")'.profile]
cxxflags = ["/Zc:__cplusplus", "/Zc:preprocessor", "/MP"]